### PR TITLE
Make the name of get_image consistent with other calls.

### PR DESCRIPTION
**Pull request by mikalstill**

### CODE REVIEW

**Comment by mikalstill** [comment]
I feel like there should be a get_image() call for a specific image as well, but that I should probably wait for Andy's proposed re-write before thinking too hard about that.

**Comment by mandoonandy** [comment]
In the future, we may want to download images. The download function might be `get_image(uuid)`? Will this be better to stay as `get_image_meta()`? 

Should we list all our current/planned/possible function calls before making changes?

**Comment by mikalstill** [comment]
So, the current naming convention is get_thing(). I am concerned about people being confused about _meta() calls vs _metadata() calls, which is frankly a little bit confusing to me. I think get_image() would return the DB entry for a single image, much as get_instance() does. I was thinking about the download case, and what about inserting into the get_thing() call a field called "download_url" or something which has the data? That would allow us to refer them to other machines, or a nfs url, or whatever if we ever wanted to...

Thoughts?

**Comment by mandoonandy** [comment]
Maybe.... [needing more convincing]

It would need authentication. Ideally the user would not have to configure that in another code library.

The flexibility of returning a download_url, can be handled with HTTP 'temp redirect` ie. when the image is on another machine. If we use NFS, then we still need to handle auth.

**Review by mandoonandy — APPROVED** [review]
LGTM

**Pull request merged**
